services:
  - type: web
    name: google-tv-afrique
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: CORS_ORIGIN
        sync: false
